# Generated by Django 4.2.20 on 2025-04-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_anniversaryreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='anniversaryreminder',
            name='username',
            field=models.EmailField(default='daveharsh38@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='birthdayreminder',
            name='username',
            field=models.EmailField(default='daveharsh38@gmail.com', max_length=254),
        ),
    ]
