# Generated by Django 4.2.20 on 2025-04-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_eventreminder_delete_anniversaryreminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('occasion', models.CharField(max_length=50)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('occasion', models.CharField(max_length=50)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
