# Generated by Django 4.2.20 on 2025-04-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_anniversaryreminder_birthdayreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnniversaryReminder',
        ),
        migrations.DeleteModel(
            name='BirthdayReminder',
        ),
    ]
