# Generated by Django 4.2.20 on 2025-04-18 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_anniversaryreminder_delete_birthdayreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
