# Generated by Django 4.2.20 on 2025-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_eventreminder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='year_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
