# Generated by Django 4.2.20 on 2025-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_eventreminder_sent_eventreminder_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary')], max_length=50)),
            ],
        ),
    ]
